Debugger elements
RemcoSmitsDev/zed pull request #22
Opened 2024-08-21 23:39 UTC by Anthony-Eid

This PR aim's to start the process of cleaning up & improving the maintainability of the debugger's variable rendering and management. 

By creating a new View called `VariableList` and encapsulating the logic written by Remco that handles variable management. Post Alpha of the debugger we will be changing the variable list's internals to be cleaner as well.

2024-08-24 13:29 UTC, RemcoSmitsDev commented
Can we maybe call the module variable List instead of elements? That is more clear because it only contains variable list code.

2024-08-24 14:21 UTC, RemcoSmitsDev requested changes

2024-08-24 14:21 UTC, RemcoSmitsDev commented on crates/debugger_ui/src/debugger_panel_item.rs
> +    pub client: Arc<DebugAdapterClient>,
Can you pls use the methods for this, and if we don't have a method create one for it. So it's more inline how Zed does things.

2024-08-24 14:21 UTC, RemcoSmitsDev commented on crates/debugger_ui/src/debugger_panel_item.rs
> +    pub thread_id: u64,
Can you pls use the methods for this, and if we don't have a method create one for it. So it's more inline how Zed does things.

2024-08-25 20:21 UTC, Anthony-Eid commented on crates/debugger_ui/src/debugger_panel_item.rs
> +    pub client: Arc<DebugAdapterClient>,
fixed

2024-08-25 20:21 UTC, Anthony-Eid commented on crates/debugger_ui/src/debugger_panel_item.rs
> +    pub thread_id: u64,
fixed

2024-08-25 20:23 UTC, merged