dap_adapters: add gdb
RemcoSmitsDev/zed pull request #70
Opened 2024-11-26 20:54 UTC by jansol

Nothing special here, just launching gdb with `-i=dap`. Nicer to have it as a builtin type instead of a custom DAP though.

2024-11-26 21:01 UTC, RemcoSmitsDev commented
Hey, yeah totally agree, thanks for adding this! 
Do you have a task example that we can share inside a specific Zed channel for GDB?

2024-11-26 21:01 UTC, Anthony-Eid commented
Thank you for implementing this!

2024-11-26 21:04 UTC, Anthony-Eid commented
> Hey, yeah totally agree, thanks for adding this! Do you have a task example that we can share inside a specific Zed channel for GDB?

I think it would be similar to lldb

```json
{
  "label": "LLDB Debug Zed",
  "program": "$ZED_WORKTREE_ROOT/target/debug/zed",
  "adapter": "lldb",
  "request": "launch"
  "initialize_args": {
      "stopAtBeginningOfMainSubprogram": true
   }
}
```

2024-11-26 21:04 UTC, RemcoSmitsDev commented
Would it be similar to LLDB? I would like to add a default config for debugging Zed with GDB inside the `/.zed/debug.json`.

```json
  {
    "label": "Debug Zed with LLDB",
    "adapter": "lldb",
    "program": "$ZED_WORKTREE_ROOT/target/debug/zed",
    "request": "launch",
    "cwd": "$ZED_WORKTREE_ROOT"
  }
```
GDB debug task example??
```json
  {
    "label": "Debug Zed with GDB",
    "adapter": "gdb",
    "program": "$ZED_WORKTREE_ROOT/target/debug/zed",
    "request": "launch",
    "cwd": "$ZED_WORKTREE_ROOT"
  }
```

2024-11-26 21:54 UTC, jansol commented
I have this left over in the project where I tested last time:
```json
  {
    "label": "Launch in GDB",
    "adapter": "gdb",
    "session_type": "launch",
    "program": "$ZED_WORKTREE_ROOT/build/main-binary",
    "initialize_args": {
      "args": [],
      "cwd": "$ZED_WORKTREE_ROOT",
      "env": {},
      "stopAtBeginningOfMainSubprogram": true
    }
  }
```

But it seems the format has changed since then?

2024-11-27 10:47 UTC, RemcoSmitsDev requested changes
Could you also add this to the `.zed/debug.json`? I wanted to push this change, but I cannot to your fork.

```json
  {
    "label": "Debug Zed with GDB",
    "adapter": "gdb",
    "program": "$ZED_WORKTREE_ROOT/target/debug/zed",
    "request": "launch",
    "cwd": "$ZED_WORKTREE_ROOT",
    "initialize_args": {
      "stopAtBeginningOfMainSubprogram": true
    }
  }
```

2024-11-27 10:47 UTC, RemcoSmitsDev commented on crates/dap_adapters/src/gdb.rs
> +        json!({"program": config.program})
Can you also pass in the **cwd** key? So other people don't have to think about adding it to their `initialize_args`.

2024-11-27 11:41 UTC, RemcoSmitsDev commented
I also saw that GDB support attach, we might want to implement that as well. Happy to help to make that work, but cannot get GDB to work on my MacBook.

2024-11-28 19:30 UTC, jansol commented
Attaching to a process with GDB is indeed possible, but requires special permissions (SYS_PTRACE capability or root) so that should probably wait until we have some form of polkit integration for escalating privileges.

2024-11-28 19:43 UTC, RemcoSmitsDev commented
Alright, thanks for the clarification and your contribution!

2024-11-28 19:54 UTC, Anthony-Eid commented
We should add a cfg flag to disable gfb on m series macs because there’s no arm port available.

That way people can’t select it when it’s bot possible to use

2024-11-28 20:14 UTC, merged

2024-11-28 20:45 UTC, jansol commented
GDB is apparently perfectly fine on aarch64, just not on macOS.